[package]
name = "vanityssh-cl"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22"
ed25519-dalek = { version = "2.1", features = ["asm"] }
sha2 = { version = "0.10", features = ["asm"] }
opencl3 = "0.12"
rand = "0.9"
rayon = "1.10"
regex = "1.11"
